/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.baitap1;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import thuchanhobject.bai1.CanBo;
import thuchanhobject.bai1.GiangVien;
import thuchanhobject.bai1.Person;

/**
 *
 * @author Admin
 */
public class FormNhanVien extends javax.swing.JFrame {
    ArrayList<Person> lnv;
    int change=0;
    /**
     * Creates new form FormNhanVien
     */
    public FormNhanVien() {
        initComponents();
        changeStatusButton(true,false,false);
        lnv=new ArrayList<>();
        showData();
        change=0;
        disableView();
        resetView();
        setTitle("Phần mềm quản lý nhân viên");
    }

    private void changeStatusButton(boolean them,boolean sua,boolean luu) {
        btn_them.setEnabled(them);
        btn_sua.setEnabled(sua);
        btn_luu.setEnabled(luu);
    }
private void showData() {
    
       String columns[]={"Mã NV","Tên NV","Giới tính","Quê quán","Hệ số lương","Thực Lãnh","Chức vụ"};  
	DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
	jTable1.setModel(model);	
		  
    for(int i=0;i<lnv.size();i++){
        
    String gt="Nam";
    if(!lnv.get(i).isGt()){
        gt="Nữ";
    }
           String ar[]=lnv.get(i).toString().split(";");
   model.addRow(new Object[]{ar[0],lnv.get(i).getName(),lnv.get(i).getQuequan(),gt,ar[1],ar[2],ar[3]});
    }				
}
private void showDataLoc(int vt) {
    
       String columns[]={"Mã NV","Tên NV","Giới tính","Quê quán"};  
		DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
	jTable1.setModel(model);	
		  
    for(int i=0;i<lnv.size();i++){
        if(i==vt){
    String gt="Nam";
    if(!lnv.get(i).isGt()){
        gt="Nữ";
    }
 //  model.addRow(new Object[]{lnv.get(i).getManv(),lnv.get(i).getName(),lnv.get(i).getQuequan(),gt});
    }	
    }
		
		//return tableJPanel;
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttennv = new javax.swing.JTextField();
        cb_gt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtquequan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txthsl = new javax.swing.JTextField();
        rdGV = new javax.swing.JRadioButton();
        rdCB = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txttim = new javax.swing.JTextField();
        btn_tim = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_lamlai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));

        jLabel1.setText("Mã NV:");

        jLabel2.setText("Tên NV:");

        cb_gt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jLabel3.setText("Giới tính:");

        jLabel4.setText("Quequan");

        jLabel6.setText("Hệ số lương:");

        rdGV.setText("Giảng viên");
        rdGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdGVActionPerformed(evt);
            }
        });

        rdCB.setText("Cán bộ");
        rdCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmanv)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cb_gt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 234, Short.MAX_VALUE))
                            .addComponent(txttennv)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtquequan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthsl, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(rdGV)
                .addGap(18, 18, 18)
                .addComponent(rdCB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_gt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtquequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txthsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdGV)
                    .addComponent(rdCB))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Tìm:");

        btn_tim.setText("Tìm");
        btn_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timActionPerformed(evt);
            }
        });

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_lamlai.setText("Làm lại");
        btn_lamlai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamlaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_them)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_sua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_luu)
                        .addGap(2, 2, 2)
                        .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btn_lamlai)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_tim)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_them)
                            .addComponent(btn_sua)
                            .addComponent(btn_luu)
                            .addComponent(btn_xoa)
                            .addComponent(btn_lamlai))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        changeStatusButton(false,false,true);
        enableView();
        change=1;//them
        
    }//GEN-LAST:event_btn_themActionPerformed
private void resetView(){
    change=0;
    txtmanv.setText("");
    txttennv.setText("");
    cb_gt.setSelectedIndex(0);
    txtquequan.setText("");
    txthsl.setText("");
    rdGV.setSelected(true);
    rdCB.setSelected(false);
}
private void disableView(){
    txtmanv.setEnabled(false);
    txttennv.setEnabled(false);
    txtquequan.setEnabled(false);
    cb_gt.setEnabled(false);
    txthsl.setEnabled(false);
    
}
private void enableView(){
    txtmanv.requestFocus();
    txtmanv.setEnabled(true);
    txttennv.setEnabled(true);
    txtquequan.setEnabled(true);
    cb_gt.setEnabled(true);
    txthsl.setEnabled(true);
}
    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        if(change==1){ //them
        //JOptionPane.showMessageDialog(null, "Đang chuẩn thêm dữ liệu");
        changeStatusButton(true,false,false);
        String manv=txtmanv.getText();
        String tennv=txttennv.getText();
        String gt=cb_gt.getSelectedItem().toString();
        boolean sex;
        if(gt.equalsIgnoreCase("nam")){
            sex=true;
        }else{
            sex=false;
        }
        String quequan=txtquequan.getText();
        
      //  lnv.add(new NhanVien(manv, tennv, sex, quequan));
      
      //      System.out.println(""+new NhanVien(manv, tennv, sex, quequan));
            //Gọi hàm xuatDSNhanVien
        //  NhanVien.xuatDSNhanVien(lnv);
        float hsl=Float.parseFloat(txthsl.getText());
        
        if(rdGV.isSelected()){
          //  JOptionPane.showMessageDialog(null, "Đang chọn giảng viên");
          Person p1=new GiangVien(manv, tennv, sex, quequan,hsl);
            lnv.add(p1);
        }else{
            //JOptionPane.showMessageDialog(null, "Đang chọn cán bộ");
            Person p1=new CanBo(manv, tennv, sex, quequan,hsl);
             lnv.add(p1);
        }
          showData();
          resetView();
          disableView();
        }else{ //update
            JOptionPane.showMessageDialog(null, "Đang chuẩn sửa dữ liệu");
            disableView();
       
        changeStatusButton(true,false,false);
        String manv=txtmanv.getText();
        String tennv=txttennv.getText();
        String gt=cb_gt.getSelectedItem().toString();
        boolean sex;
        if(gt.equalsIgnoreCase("nam")){
            sex=true;
        }else{
            sex=false;
        }
        String quequan=txtquequan.getText();
       // lnv.remove(WIDTH)
       int row = jTable1.getSelectedRow();
       lnv.remove(row);
       // lnv.add(row,new NhanVien(manv, tennv, sex, quequan));
        showData();
        resetView();
        }
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        change=2;//sua
        changeStatusButton(false, false, true);
        enableView();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        changeStatusButton(false, true, false);
        int column = 0;
        int row = jTable1.getSelectedRow();
        String manv = jTable1.getModel().getValueAt(row, 0).toString();
        String hsl = jTable1.getModel().getValueAt(row, 4).toString();
        String cv = jTable1.getModel().getValueAt(row, 6).toString();
        if(cv.equals("GV")){
            rdGV.setSelected(true);
            rdCB.setSelected(false);
        }else{
           rdGV.setSelected(false);
            rdCB.setSelected(true);
        }
        txtmanv.setText(manv);
        txttennv.setText(lnv.get(row).getName());
        txtquequan.setText(lnv.get(row).getQuequan());
        txthsl.setText(hsl);
        if(lnv.get(row).isGt()==true){
        cb_gt.setSelectedItem("Nam");
        }else{
             cb_gt.setSelectedItem("Nữ");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_lamlaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamlaiActionPerformed
        // TODO add your handling code here:
        resetView();
        changeStatusButton(true,false, false);
        disableView();
    }//GEN-LAST:event_btn_lamlaiActionPerformed

    private void btn_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timActionPerformed
        // TODO add your handling code here:
        String s=txttim.getText();
    //    int vt=NhanVien.timNhanVienX(lnv, s);
    int vt=-1;
        if(vt==-1){
            JOptionPane.showMessageDialog(null, "Không tìm thấy");
             showDataLoc(vt);
        }else{
            showDataLoc(vt);
        }
    }//GEN-LAST:event_btn_timActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
         int row = jTable1.getSelectedRow();
        lnv.remove(row);
       // lnv.add(row,new NhanVien(manv, tennv, sex, quequan));
        showData();
        resetView();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void rdGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdGVActionPerformed
        // TODO add your handling code here:
        rdGV.setSelected(true);
        rdCB.setSelected(false);
        
    }//GEN-LAST:event_rdGVActionPerformed

    private void rdCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCBActionPerformed
        // TODO add your handling code here:
        rdGV.setSelected(false);
        rdCB.setSelected(true);
    }//GEN-LAST:event_rdCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_lamlai;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_tim;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_gt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdCB;
    private javax.swing.JRadioButton rdGV;
    private javax.swing.JTextField txthsl;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txtquequan;
    private javax.swing.JTextField txttennv;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
